### ISSUE TITLE
Weird things happen while copying dir in MC

### ISSUE THREAD

**Issue by Detuner** [yandex-cloud/geesefs#4] opened 2021-09-30 13:40 UTC
I mounted YC s3 bucket in YC compute VM to run some tests. Put a dir with about 1k files (random docs, several kb to 50Mb in size, ~1,5Gb total). Then tried to copy directory from mount point to local FS with Midnight Commander and got some strange results. At random point it shows a warning dialog, telling me that the target file already exists. If I choose to overwrite all existing files, it goes on copying and shows really weird info like this:

![image](https://user-images.githubusercontent.com/37659799/135463384-e4fde1b0-5191-450c-8453-21fa93c40e3d.png)
Note, that processed files counters show correct number of files and total source dir size at the right side.

Eventually it gets the job done and all the files are actually OK, but this behaviour is really weird.
This issue seem to happen only in MC, cp -ir works just fine. It also seem to depend on the number of files in dir. With ~1k files it  happens every time I try, with ~500 files it happens sometimes, and with ~300 files I couldn't reproduce it.

**Comment by vitalif** [comment] 2021-10-01 13:53
OK it seems I reproduced the issue, so I'm looking into it :-)

**Comment by vitalif** [comment] 2021-10-05 09:49
Try v0.28.5, the issue should be fixed in it, at least it doesn't reproduce for me anymore.
The problem was that directory position could be reset when directory was refreshed from the server and listing could return duplicates. Now the position is saved using current file name so it's not possible anymore. :-)

**Closed by vitalif** 2021-10-05 09:49 UTC
