### ISSUE TITLE
MacOS' finder 'cannot list files

### ISSUE THREAD

**Issue by wenbingzhang** [yandex-cloud/geesefs#81] opened 2023-06-30 03:30 UTC
VERSION:
   0.36.2

<img width="705" alt="iShot_2023-06-30_11 24 25" src="https://github.com/yandex-cloud/geesefs/assets/13162606/bf19b42e-8804-4e1c-8731-37476dc8341d">

<img width="1234" alt="iShot_2023-06-30_11 22 38" src="https://github.com/yandex-cloud/geesefs/assets/13162606/b114c657-4981-43d7-85a2-d54717071660">

[test.log](https://github.com/yandex-cloud/geesefs/files/11912498/test.log)

**Comment by wenbingzhang** [comment] 2023-06-30 03:39
The same configuration cannot be uploaded on Windows

[test.log](https://github.com/yandex-cloud/geesefs/files/11912541/test.log)

**Comment by wenbingzhang** [comment] 2023-06-30 03:47
> VERSION: 0.36.2
> 
> <img alt="iShot_2023-06-30_11 24 25" width="705" src="https://user-images.githubusercontent.com/13162606/249985644-bf19b42e-8804-4e1c-8731-37476dc8341d.png"> <img alt="iShot_2023-06-30_11 22 38" width="1234" src="https://user-images.githubusercontent.com/13162606/249985697-b114c657-4981-43d7-85a2-d54717071660.png">
> [test.log](https://github.com/yandex-cloud/geesefs/files/11912498/test.log)

<img width="891" alt="image" src="https://github.com/yandex-cloud/geesefs/assets/13162606/cd9787d1-8e72-4ce1-a602-8a9e5578c4ce">

**Comment by vitalif** [comment] 2023-08-11 11:03
Hi
Windows version had a bug with CreateFile - apparently, Windows expects Create to overwrite existing files. I fixed it in 0.37.1, you can retry.
Mac Finder bug reproduces in our tests too, we're investigating the cause, but seems it may be a more general problem with macfuse/osxfuse https://github.com/osxfuse/osxfuse/issues/925

**Comment by vitalif** [comment] 2023-08-11 11:29
Okay, this was caused by geesefs returning ENODATA for non-existing extended attributes, while MacOS expects ENOATTR.
Fixed in master, I think I'll build a release for this fix.

**Closed** 2023-08-11 11:28 UTC

**Comment by vitalif** [comment] 2023-08-11 12:50
https://github.com/yandex-cloud/geesefs/releases/tag/v0.37.2
